# Generated by Django 5.0.3 on 2026-04-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.CharField(max_length=100)),
                ("message", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("open", "待处理"), ("resolved", "已处理"), ("ignored", "已忽略")], db_index=True, default="open", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="flags", to="posts.post")),
                ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_post_flags", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="post_flags", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "post_flags",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="postflag",
            index=models.Index(fields=["post"], name="post_flags_post_id_8dc228_idx"),
        ),
        migrations.AddIndex(
            model_name="postflag",
            index=models.Index(fields=["user"], name="post_flags_user_id_3dffd5_idx"),
        ),
        migrations.AddIndex(
            model_name="postflag",
            index=models.Index(fields=["status"], name="post_flags_status_d951be_idx"),
        ),
        migrations.AddConstraint(
            model_name="postflag",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "open")), fields=("post", "user", "status"), name="unique_open_post_flag_per_user"),
        ),
    ]

