# Generated by Django 5.0.3 on 2026-06-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_transfer_extension_owned_models_state"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="posts_discuss_49d427_idx",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="posts_user_id_05c508_idx",
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="type",
            field=models.CharField(default="comment", max_length=50),
        ),
    ]
